spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sys_car_rental?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.gmail.com
    port: 587
    username: thithptquocgia2003@gmail.com
    password: tyqz haof nkfv dora
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
    smtp:
      debug: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  quartz:
    job-store-type: memory
    jdbc:
      initialize-schema: never
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 10
          jobStore:
            misfireThreshold: 60000

cloudinary:
  cloud-name: dtcokd0bb
  api-key: 559642131997974
  api-secret: Eqw5VSxMsVndbWnmb3cfLMhKEhA
  folder:
    default: RentalCar/Default
    avatar: RentalCar/Avatar
    car: RentalCar/Car

app:
  jwt:
    secret-key: evqSvEusWnP73XRuchvNKK4FFNa+jgevEgsMbnmdS42eqN98e7TdW3+JA6lSHZthj8Lb7iR9ElYdLMAZZoqx4sx2kngytOo+kuFgPtOOFqp/iKd6AbuUgDiSYySg5gatWCb0YRas4jtaHtyCZ4JN6TdXXjyNYv59MBzF77zpVYl2Q0cSFtKgNv3crI8I8tZtKsXuaX0aHCknplAIJlu9xNR1+yn3wV5qfHnjORlbKaiLqpJ98wlfhTvOyKDNdasniKAzAQM1EOwwOFDTTeJrPN5W1bv8efehi9d43MaiOO/xOFKKmfUKhBTQbdd1VR5ulB90EDiszn6yx5pcb2PxueQpfm2/EQQoazIGDw2YDNU=
    expire-seconds: 30000000
    issuer: rental-car.com

springdoc:
  swagger-ui:
    operationsSorter: method
    tagsSorter: alpha

openapi:
  dev-url: http://localhost:8080
  prod-url: http://localhost:3000
  contact-email: thongpdvn@gmail.com
  contact-name: Rental-Car
  contact-url: http://localhost:8080/contact
  title: Rental Car API Documentation
  version: 1.0
  description: This document exposes endpoint APIs to manage Rental-Car system

vnpay:
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payment/vnpay/return
  ipn-url: http://localhost:8080/api/v1/payment/vnpay/ipn
  tmn-code: TB3ID2OY
  secret-key: D37EH8RZH2J511RT2ANXQOPV3AAH9Y0G
  api-url: https://sandbox.vnpayment.vn/merchant_webapi/api/transaction
  version: 2.1.0
  command: pay
  order-type: wallet_topup
  curr-code: VND
  default-locale: vn
  expire-minutes: 15

